access_token_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA5FeB4ED8okDpvZNm58G8DBx1SsvVGfbSgNYWRXBb1dI4o4Tx
  AMzQ/sJLiGqpYrzbLHH6loC5ILsNcUe1QJ6dADhjFqRMoS88hi3XXq/2h/JVKgSL
  Lbfg2efixwW5JUVNi4tm97T6D5nJmGww+vY6jwmN81QsbOjmGpGw8P1ihLENc6Ya
  /En3Suo11ELJnoIstHhsGWILSegdfo8dnGjfaKOFKdkLena6JTnP1HVv6eGQOznx
  VPBovtxbyYDFAXLVR8qfnaqlQE7IHQoIybzarZmh9g2Yxr1e6TgCPJvJarTIhyFl
  4rGb/fWz0Z7V21Zq08kSmHtv8ppzMexvcPIjnYJ9zKxErUayxNmnwaixHK7BOBFp
  MlSV+Vz8jZ+fJdCgUElMYta1/0+jkZt6MbiG1BlpuPF+q43OnM2Mx89nKeEIxIMA
  B1XQv4/AKFJ7PzVRiOc4UDfqFzJwxz8prNvN2PVyksfOZIveL63GGGoF8yH0R76N
  87uO29l/ioKuxCNA4cmvzhYXpm10esHbSgkIZY7sYvA924QARjTMVlcOsfHb5Pvq
  yE0KuWu/T0EO4fZ+EKNQtydHbETMMAR+GoGI+BV3aF4jMNVTZlQ1OTgfib578j63
  LzyrPEv3XXewwkgNCKygu8jlDxdvFfkhiibrJk/ntspCCSPmIBphh/wn9rECAwEA
  AQKCAgEAqQt3pRO3dE9mO+jSOCUfGEBBPVxlqVEnSiY0Wrfx5Pw63iPfX95Bozko
  PhfoyqZSBDdlcuJdK7QPIZwavXovdShJg0ujR3j278ckOH9AnihzkCXI+9Gzbt7S
  7tB33vXNkM9lLWEX91C9BFCkekar15UVN91K/l31bBoLyn1r4BxLfyCrvbbsktON
  glTneqeYfQrhzHDfNpnWrAk7vL2PF6JnRTHf44veBw0jpYBDl/xbkN02otFQWmw8
  r5LbRlVDPGDvhgP9TvyD/aueEev0YKzqUISEZC1yBGpojYIvvQWVpyS8jvU6LOsn
  crqKTFVPxPaJA8XufMaHHaCSaCV64wya+3KCxei0kF9HBBtK5vh9O9I0goMKAYic
  dZwwo6hS/ysVlrxcGfIpsaj0RW1Nma4X6sb5YNOWgKeHYEJBo61GYvPfpraWcJ6T
  Lzrb3+XB7MZpN6s+XZWU3U5SdL9DwuW5Tg2mtK/Zx9xBWxnKOtCOt1i2l6QyBYJ0
  KVJ9roVCgUaGhxvRPWxaTuaeJsxLTX4Lbx9qhHixMGUpHI1ulGJsuqFxOf7JF6KI
  GaIHeEsbMZNayahXGP26JQXQEsyuVSndsjI+h3/Szy7ODmOde57rzYOLhYUuY/uF
  lTuPRGKV7VzEKtZnZKPe3+ilKRNzGXPKeYfDlAlwI5Cp4nEPnbkCggEBAPwDQD+p
  TQhGgeizubrcLuyYhyj1L2NGcUvpJsZ8tYFMOj1v+LA4qYVA4+VdtkR0txKnpqTp
  zhyHwKobE8GW8yOJ8YKbjwL2kYLf2RryRQTRNlw+HJEF+utCMaGM/5tZAiFFkqQv
  IYJl/m2kFhqyLNhCmws6g59+43IrMMXQatn+8fzPs9eJ8Oq8oSyVPpS2pif4HqU6
  WXgCPtpTC0GLKaIP1fHstdDdriK1874ZXCT0hNMsIef5GTYjqmuFEte4W+7Kk3Q5
  MshtfZHhzsaNjhbbTNXotlnTQ/c7cqcgGvX+qxyhfAAip4HBFAr+rg24sd5U/EmE
  NZxg9C5EHfe83xMCggEBAOf0YVGcm8D1ViM4KbpcSbVDKpWnfqfBSZn81rb+tTGA
  uiGTGvvPSVOKujEgHEJMZCdeSlG1lxpjgmsjvZBfd93/Ze00TdOJkkPF2BYZF7qI
  Way/DZCCJ7exghY14xKMkk/yxX4GGNKqmsSC2ELzzenTEGqxAfHn4cE9rzDWnmmY
  sDbeXP0n9oyxJG3aeQWGbaSDpCvPntwwolce4Ojb5wc4QDmDLW0fN7xRCqp+mgjb
  kcBaoQdfSUqlFpfRFZwyIQqO1yFP9GnwuybokANmXKH8HYkCFz9/X48NEG3qPIml
  g2avdi5JWR7mbzem2v9qbAyq9hfcsbkzqBUH7D6C16sCggEBAKXsSgfgIuy4511b
  v4Qs5eQ2hH7N91ZIkd2l8zap8yLfGlVK/JShqdMnJyTjr1ag9cwdf5WCroaQRqR4
  0WgbR5f1gYI5g04zIxjk4t9f9Vs3l6/h4RMGue7dFSpFWCFi2Akp8mOQ+GIPXxW2
  /Cq1dtsn90bMTs7bT0ri7ui+0SsYNSD7a3AUzP7wFLnyxVJKc1lLfnnQ0gk2iUVb
  ecS8qDuga38uF4MeAUGvRHy727QlHbKfku9VTWkc0F6cLgzDwBuXWsAhzLKzjAJZ
  hrepiYy49Hy+DBlWBKCpjlJEzBt8ghKGq8q3Bkxi4BxhFB3Kpak5kSWiG14LY5l2
  lbh/rOsCggEACbnZis6CSWkAH6HvPf04qf0TAAtx6B7WszpC1pF/j3/STi4Y544d
  iP88J2stRCpn2K6/dwWiPF0Hzu5EuJUINarL31JeIQyXsXfOQ77xm8Sz3eZ07yZF
  /BHZXo0L5G84g1mupkYjLFIzAyJpZwVKEQ/klFSvvDD46l1nxyh4o/zfBq30QDk4
  wVV8LY8HnA+y8T8D10JxatIvPG/zBlCSM19Mchzp/rVcZO0RAW0lkFGEnwgt0F1S
  eWrKs7r0qQQBFqw+oQr1OKv7bPo7b6kPIUutAV2xE9yHaTwnADTeLPdftyKMVgyF
  TCJlb3PzotoXhcB1aTK70QQ1fAxE/6oE2QKCAQBHCkqt79c60pX/rxu50M0WbAOK
  LaBuqNCxkhYaECcl/JzVnmGjINsSEN/lnI4rWxKLxJ3JKutKeZ+4wryY3PZm4THj
  NU5PQlOkALj+vXHAVYB35Ou8fZom8nCVQ+geEpyq9b7QugtwB5AYJ06BbCSf0sV1
  qmirOV/olXVARF7jKymNwegxVWTWoZaKtHWWSDwX7+OZjqydgDU3nCO2NGnBDiuK
  GiQ3TZlCIJY8o1fHFdHrJ/uXFd/2GRVifjxQdiA1ve8UrpBwStR4/QpoKOndwu1Z
  KykKWyKhtrgOM9r/JsgkAtwPt6vnSKIY5isvxDKhZvu50ad8grIYvqkhY5PG
  -----END RSA PRIVATE KEY-----

access_token_public_key: |
  -----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5FeB4ED8okDpvZNm58G8
  DBx1SsvVGfbSgNYWRXBb1dI4o4TxAMzQ/sJLiGqpYrzbLHH6loC5ILsNcUe1QJ6d
  ADhjFqRMoS88hi3XXq/2h/JVKgSLLbfg2efixwW5JUVNi4tm97T6D5nJmGww+vY6
  jwmN81QsbOjmGpGw8P1ihLENc6Ya/En3Suo11ELJnoIstHhsGWILSegdfo8dnGjf
  aKOFKdkLena6JTnP1HVv6eGQOznxVPBovtxbyYDFAXLVR8qfnaqlQE7IHQoIybza
  rZmh9g2Yxr1e6TgCPJvJarTIhyFl4rGb/fWz0Z7V21Zq08kSmHtv8ppzMexvcPIj
  nYJ9zKxErUayxNmnwaixHK7BOBFpMlSV+Vz8jZ+fJdCgUElMYta1/0+jkZt6MbiG
  1BlpuPF+q43OnM2Mx89nKeEIxIMAB1XQv4/AKFJ7PzVRiOc4UDfqFzJwxz8prNvN
  2PVyksfOZIveL63GGGoF8yH0R76N87uO29l/ioKuxCNA4cmvzhYXpm10esHbSgkI
  ZY7sYvA924QARjTMVlcOsfHb5PvqyE0KuWu/T0EO4fZ+EKNQtydHbETMMAR+GoGI
  +BV3aF4jMNVTZlQ1OTgfib578j63LzyrPEv3XXewwkgNCKygu8jlDxdvFfkhiibr
  Jk/ntspCCSPmIBphh/wn9rECAwEAAQ==
  -----END PUBLIC KEY-----

access_token_expired_in: 30

refresh_token_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA1BtdWiHvqspqgAKR+iMjqZHZFy5npXMTZG0MzxNZx12nyRo6
  I0puTtgQNgngTZ2k4AF8tluWHI0jx7maXle6tZsrIf1/F9SLNACXb3X+6DON4n6I
  DpTUvTufsOzj+8oTh1HJz9Ml+KnAC4d4N980MrFa62U+hxcrab4Y+oz+z9Sh4EoJ
  1F2cIK5rpRF+bLCOhKZD5Fu8F/F3nJg5MNaW1nwLQvJD4yM9gOr5s1t8iz4NfeeA
  iZsQ6RbBT6f6Fz2HOjI/bqKdIwxVQ2EpzmN0757P5QefN8dxL8bauSQH/0ofeeD9
  zSZXlOmnS1q6VPsufA/Q34lXfpu+XyGY5d649U7GWxUQX/KKQ/NkFS+CIzL+TR5l
  RC6V5vSkc7SR/xOWju1YY9oHqX93vtJXvMgm/20v3PD+AzLR+DN3/v9+1oc9C62b
  s+B3282iJEgCGYT9SLQVEnpq0ZYfhknICBlxV9gE6icMCuw3XNd/g3WKJ26/zXfS
  AivE+f4kZ3ZtulLHINW9cFE7FaCUiPDgLWllCxFMTqOUeVSoL/iLq4chWuMC1UBr
  0L84aoa7XANYW2w9NyPgh91fzY5djntMtjPd3YM8WXPdOL5iVxIs0SvOalOmyyui
  IbjO2oxQavuJYpFTnson4dknMggg4Elv0TATFzPJKPmjBHOJzORFdbvl9wkCAwEA
  AQKCAgBJFQisRqcirM3XP4t2qWbfRV6MizOxIR5cauqP6vXzKIToWL4RbNLnHbEw
  PWTouVmWyUxkNNhbDBJ4/a1/tjCh5E4PTx3cYyJ3j4CeKgTjkuffU4OjqopGjWWv
  e1/uYKkr5fVoQzOBI1QFZO76KVD96ngORXsu5r/Rlmta4PvnNjd0ZW5PmtVxuUdj
  v8xUvNzOPc+Evkrn4Q46iYSjHD0qt+DVd04G1Byb79qLfwlBnObfK8XxI9nGxk1j
  Gdik61FNrwSGJUeJTPWP2smh0Ej5SzoMivzEJlcMhDLWueB7iNmhj/FDH2Pr7jnz
  T9aF82oH2xc3/kWEXTtR4eyhv4Twd+Shx8kOVOiUq10qyDf11w5VTgFRwy5+Y4Hp
  gstLdg9KgQDhenYaWWn4/KxK5KBWFwfOL+gF6Mq9TTneI/2OO4fUaQ3E0b1tmw5b
  zh4RwT8ADEfjnpxqXFP/T3HaD6QtzKqAOonGqWxICbvI10usYfR5Mvfo+SquXUTK
  /ATGoguLax0svEn+K9NM8T30dbENGv+rhdW3kl+esZbF+FtYPGi6CzPheXfJ0tkI
  /QsNEjOPtWTjzzG4Ku938NKnnjTXVwzYR+zF0+QZE5hxumsGdyuVVeQrdiBJMpan
  jjGNxJL35MXEmZZy7jHGnzkQicvnYjFXmQiIbEIJfwjhLkKm1QKCAQEA+zJ37bvS
  CudUPhpFppLrqHVhrf9TG+egRV2ia83Q17/Yy7NlCKA9GUAX/RSMFME4e4AtFKLd
  7/U69Ihhp9Z7nGSgEtD5vnxkBZrIcyFsyQUa4kDnGu7ioe3p5a0QnqqByY2i4o//
  iATFc6tBRf/TDGkYFbtd0b0HM51te0PlkdU4zIgy6dP0qGIIM328sfVF3SjIGM1W
  La7Nx3zvc8bbFWjHKf13nYH9ETtZ9wCozCClXbOl6LVwBQRhIWWdtmffahtD+itX
  AFL97sq/tVs2fOk2S1zuW3WQRJE2IzjcW/8Im8tu0oJEyLVnJHGKy2AhI1hOYVBy
  JqcaK48prN874wKCAQEA2CmPxuCTaj1CiWHSGqDyJbxlkX68/yIICV46Z2aoucLd
  iQ5SWEjccq8070FEk0zOFQwmFf2j7mIYSxwnRQAcsBLojPhZNQ9CIR1x17DM2So3
  jg6futwSOeDITjBr/s3k4xNyPtmbL+xr8lBqGiz5LrY4gGEr/2J06tjfMam0Y4Dw
  iuVoGuGkY8HOBIlXPxPdJZLE7144bkJBviy/pTBL3CXEQxl7umg+m4DNrpAQWGME
  sotUHjWf4mSbMRU4hMG3oPpdSUv3Hc0suTTdM2rWToDyGxp6nTZ4fbw2OtTfVoz7
  lPQCTGlPpTHwsVwaNvvA+NzxYMgBhLE0J6PZc6TNIwKCAQEA3b3DWDzAQZfLKbcP
  XOe810wnGe2Vc8CYHiN1ySw5+voDam3F9kNdK/kENAf7UCbwsTSIlvreZ4BWtp3d
  dsdC/t9k3rdSfvBXawsjf142JY04Ghmo6IGP1dmq63BGh4mEYGODMfRjYbK0ilLW
  n/AgYYg0Fpr7SrZOsSV7C6D3+i/6n7JrHzZXdnxzOOD5vS4CqiPh3uMD+/ee90Y2
  KkGUC+YeSdbRzFx/BMMbu4r9dpQq5fg7sJzZcdRX2Z9WBTrUYVoIO8IeXs7kEfMw
  H+uQwdssboJudpXk8GIvJBCBlUQgWUbPYUxVY8eecPE50CXfms/NAOJ+odhIpcMO
  yueUeQKCAQAkWdDo4+lGa2jeC4o2miw+dlEqR4Lm8MUjNipiKxxiqMdyfesRF6ei
  zZ38QiCTGM5rMbDR7+Z6dxqYvvJHoz4vye47jqQJzTgUs4vqdrvsJTJUfFcWKF4U
  R53HsFLo9ZzxJtsGgLedNofspuNA5aE93rzfsfehKeB5geD+zAge15cb9HouUxW/
  BN9tWd9HJ0MAR49ApbqdqBzAK2xLDjUjn2JC2m05KsCki+OK4IUvJ++pSs7piaEK
  hFqoxWXMxXro4lF/uvuikldcCezM8cF6UCrmrexCtd9LXbRM7nFkb677HJGqYedX
  428TlGaAKpQIBbe9y8SdmOMpa19tGCC7AoIBAQDqQVOZ7uI27ujvTyTWUkLz9iKn
  J/N42r8bVWxIORGhT2DaDSJmVcM/yaUlkPWdZsSzWW48U3eX9YmKM9+LH8GtuDUO
  zuLyyszDcjAQFZfeMe7b1iWt0VWpbH/bW2x40hNDHNJ4AZroxOFRIXxu8LqVn4/R
  vKzI++BPA3ix+EQq/AbQD4+DOolfliEmje8x5xTkp0IDgKqaMSGA1ZFaiLnulYqz
  Sblm3WRaRO4oA4J1mBByMZU4Tbg8JKsOvrP1pylF9ctNT0tkYZA5sqVyNmyWGiyX
  txlxOvZjDEfkVUGZrh8NKSpt5suqS1TClkWAUlRNK6i9LgkJpLFLzlcjIcg+
  -----END RSA PRIVATE KEY-----

refresh_token_public_key: |
  -----BEGIN PUBLIC KEY-----
  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1BtdWiHvqspqgAKR+iMj
  qZHZFy5npXMTZG0MzxNZx12nyRo6I0puTtgQNgngTZ2k4AF8tluWHI0jx7maXle6
  tZsrIf1/F9SLNACXb3X+6DON4n6IDpTUvTufsOzj+8oTh1HJz9Ml+KnAC4d4N980
  MrFa62U+hxcrab4Y+oz+z9Sh4EoJ1F2cIK5rpRF+bLCOhKZD5Fu8F/F3nJg5MNaW
  1nwLQvJD4yM9gOr5s1t8iz4NfeeAiZsQ6RbBT6f6Fz2HOjI/bqKdIwxVQ2EpzmN0
  757P5QefN8dxL8bauSQH/0ofeeD9zSZXlOmnS1q6VPsufA/Q34lXfpu+XyGY5d64
  9U7GWxUQX/KKQ/NkFS+CIzL+TR5lRC6V5vSkc7SR/xOWju1YY9oHqX93vtJXvMgm
  /20v3PD+AzLR+DN3/v9+1oc9C62bs+B3282iJEgCGYT9SLQVEnpq0ZYfhknICBlx
  V9gE6icMCuw3XNd/g3WKJ26/zXfSAivE+f4kZ3ZtulLHINW9cFE7FaCUiPDgLWll
  CxFMTqOUeVSoL/iLq4chWuMC1UBr0L84aoa7XANYW2w9NyPgh91fzY5djntMtjPd
  3YM8WXPdOL5iVxIs0SvOalOmyyuiIbjO2oxQavuJYpFTnson4dknMggg4Elv0TAT
  FzPJKPmjBHOJzORFdbvl9wkCAwEAAQ==
  -----END PUBLIC KEY-----

refresh_token_expired_in: 60

jwt_redis_key: jwt

server_port: "3000"

# Available environment
# development, staging, production
# if not set default development
environment:

# TRACE (-1): for tracing the code execution path.
# DEBUG (0): messages useful for troubleshooting the program.
# INFO (1): messages describing the normal operation of an application.
# WARNING (2): for logging events that need may need to be checked later.
# ERROR (3): error messages for a specific operation.
# FATAL (4): severe errors where the application cannot recover. os.Exit(1) is called after the message is logged.
# PANIC (5): similar to FATAL, but panic() is called instead.
log_level: -1

database:
  postgres:
    host: localhost
    user: admin
    password: 1234
    dbname: tinder
    port: 5432
    sslmode: disable
    conMaxLifetime: 10
    conMaxOpen: 20
    healthCheckPeriod: 5
    ConMaxIdleTime: 5

  redis:
    host: localhost
    password: 1234
    port: 6379
    use_tls: false